#Not work
root = "."
tmp_dir = "tmp"

[build]
cmd = "echo '=== Building at [$(date)] ===' && go build -v -o ./tmp/main ."
bin = "./tmp/main"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "vendor"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = true
delay = 100
stop_on_error = true
log = "/app/build-errors.log"
send_interrupt = true
kill_delay = "0.5s"

[log]
time = true
level = "debug"

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
