root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ." 
bin = "./tmp/main.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
delay = 1000
stop_on_error = true
log = "build-errors.log"

[log]
time = true
level = "debug"

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true